### ISSUE TITLE
Bad file descriptor

### ISSUE THREAD

**Issue by snakems** [Castaglia/proftpd-mod_clamav#1]
Hello
If I set in config ClamMaxSize, get error Bad file descriptor.
If I set in the config variable ClamMaxSize, when the upload file get error Bad file descriptor.

Debug log:
127.0.1.1 (::ffff:10.0.0.2[::ffff:10.0.0.2]) - dispatching PRE_CMD command 'STOR eicar.com' to mod_rewrite
127.0.1.1 (::ffff:10.0.0.2[::ffff:10.0.0.2]) - dispatching PRE_CMD command 'STOR eicar.com' to mod_tls
127.0.1.1 (::ffff:10.0.0.2[::ffff:10.0.0.2]) - dispatching PRE_CMD command 'STOR eicar.com' to mod_core
127.0.1.1 (::ffff:10.0.0.2[::ffff:10.0.0.2]) - dispatching PRE_CMD command 'STOR eicar.com' to mod_core
127.0.1.1 (::ffff:10.0.0.2[::ffff:10.0.0.2]) - dispatching PRE_CMD command 'STOR eicar.com' to mod_quotatab
127.0.1.1 (::ffff:10.0.0.2[::ffff:10.0.0.2]) - dispatching PRE_CMD command 'STOR eicar.com' to mod_xfer
127.0.1.1 (::ffff:10.0.0.2[::ffff:10.0.0.2]) - in dir_check(): setting umask to 0022 (was 0022)
127.0.1.1 (::ffff:10.0.0.2[::ffff:10.0.0.2]) - dispatching CMD command 'STOR eicar.com' to mod_xfer
127.0.1.1 (::ffff:10.0.0.2[::ffff:10.0.0.2]) - passive data connection opened - local  : ::ffff:10.0.0.100:60446
127.0.1.1 (::ffff:10.0.0.2[::ffff:10.0.0.2]) - passive data connection opened - remote : ::ffff:10.0.0.2:2797
127.0.1.1 (::ffff:10.0.0.2[::ffff:10.0.0.2]) - mod_clamav/0.10b: absolute path is '/var/ftp/eicar.com', relative path is '/eicar.com'
127.0.1.1 (::ffff:10.0.0.2[::ffff:10.0.0.2]) - mod_clamav/0.10b: error: Can not stat file (9): Bad file descriptor
127.0.1.1 (::ffff:10.0.0.2[::ffff:10.0.0.2]) - notice: error closing '/eicar.com': Bad file descriptor
127.0.1.1 (::ffff:10.0.0.2[::ffff:10.0.0.2]) - dispatching POST_CMD_ERR command 'STOR eicar.com' to mod_sql
127.0.1.1 (::ffff:10.0.0.2[::ffff:10.0.0.2]) - dispatching POST_CMD_ERR command 'STOR eicar.com' to mod_quotatab
127.0.1.1 (::ffff:10.0.0.2[::ffff:10.0.0.2]) - dispatching LOG_CMD_ERR command 'STOR eicar.com' to mod_sql
127.0.1.1 (::ffff:10.0.0.2[::ffff:10.0.0.2]) - dispatching LOG_CMD_ERR command 'STOR eicar.com' to mod_log
127.0.1.1 (::ffff:10.0.0.2[::ffff:10.0.0.2]) - dispatching LOG_CMD_ERR command 'STOR eicar.com' to mod_xfer

**Comment by Castaglia** [comment]
Could you provide the full mod_clamav config that you're using to reproduce this issue, please?  And the output from `proftpd -V'?

**Comment by snakems** [comment]
root@webserver:/# proftpd -V
Compile-time Settings:
  Version: 1.3.3a (maint)
  Platform: LINUX [Linux 2.6.32-5-amd64 x86_64]
  Built: Fri Jan 18 2013 23:49:35 EST
  Built With:
    configure  '--prefix=/usr' '--with-includes=/usr/include/postgresql:/usr/include/mysql' '--mandir=/usr/share/man' '--sysconfdir=/etc/proftpd' '--localstatedir=/var/run' '--libexecdir=/usr/lib/proftpd' '--enable-sendfile' '--enable-facl' '--enable-dso' '--enable-autoshadow' '--enable-ctrls' '--with-modules=mod_readme' '--enable-ipv6' '--enable-nls' '--with-modules=mod_clamav' '--build' 'x86_64-linux-gnu' '--with-shared=mod_unique_id:mod_site_misc:mod_load:mod_ban:mod_quotatab:mod_sql:mod_sql_mysql:mod_sql_postgres:mod_sql_sqlite:mod_sql_odbc:mod_dynmasq:mod_quotatab_sql:mod_ldap:mod_quotatab_ldap:mod_ratio:mod_tls:mod_rewrite:mod_radius:mod_wrap:mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_quotatab_file:mod_quotatab_radius:mod_facl:mod_ctrls_admin:mod_vroot:mod_exec:mod_sftp:mod_sftp_pam:mod_sftp_sql:mod_shaper:mod_sql_passwd:mod_ifsession' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-O2 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_OPENSSL -DUSE_LDAP_TLS ' 'LDFLAGS=' 'CPPFLAGS='

  CFLAGS: -O2 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_OPENSSL -DUSE_LDAP_TLS  -Wall
  LDFLAGS: -L$(top_srcdir)/lib  
  LIBS: -lacl  -lssl -lcrypto -lcap  -lpam -lsupp -lcrypt -ldl  -ldl -lz

  Files:
    Configuration File:
      /etc/proftpd/proftpd.conf
    Pid File:
      /var/run/proftpd.pid
    Scoreboard File:
      /var/run/proftpd.scoreboard
    Header Directory:
      /usr/include/proftpd
    Shared Module Directory:
      /usr/lib/proftpd

  Features:
    + Autoshadow support
    + Controls support
    + curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    + ncurses support
    + NLS support
    + OpenSSL support
    + POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 30
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10

mod_clamav section:
<IfModule mod_clamav.c>
    ClamAV on
    ClamServer 127.0.0.1
    ClamPort 3310
    ClamMaxSize 5 Mb
</IfModule>

**Comment by Castaglia** [comment]
Thanks!  I've found the bug, and pushed changes that should correct the problem.
